# Services Data Cleaning & EDA – San Diego Youth Opportunity Project

**Author: Lauren Vo**

Built a clean, unified “services” dataset for San Diego County that we can use to map youth opportunity deserts.

**This notebook does the following:**

1. Loads raw service-related datasets from `data/raw/services`:
   - `ymca_sd.csv`
   - `sd_public_libraries.csv`
   - `Library.csv`
   - `Parks_SD.csv`
   - `rec_centers_datasd.csv`
   - `Recreation_Centers_SD.csv`
   - `Transit_Routes_GTFS.csv`
   - `Transit_Stops_GTFS_20251028.csv`
2. Cleans each dataset (column names, ZIP codes, coordinates, facility flags).
3. Merges overlapping sources (duplicate libraries, duplicate recreation centers).
4. Builds a unified **services master table** (YMCA, libraries, parks, rec centers).
5. Performs basic EDA (counts by provider / type, coordinate sanity checks, missingness).
6. Saves cleaned outputs to `data/interim/services` and `data/processed/services`.

In [28]:
from pathlib import Path
import numpy as np
import pandas as pd

candidates = [Path("."), Path(".."), Path("../..")]

PROJECT_ROOT = None
for cand in candidates:
    if (cand / "data" / "raw" / "services").exists():
        PROJECT_ROOT = cand.resolve()
        break

if PROJECT_ROOT is None:
    raise FileNotFoundError("Could not find data/raw/services from this notebook location.")

print("Using PROJECT_ROOT:", PROJECT_ROOT)

DATA_DIR = PROJECT_ROOT / "data"
RAW_SERVICES_DIR = DATA_DIR / "raw" / "services"
INTERIM_SERVICES_DIR = DATA_DIR / "interim" / "services"
PROCESSED_SERVICES_DIR = DATA_DIR / "processed" / "services"

INTERIM_SERVICES_DIR.mkdir(parents=True, exist_ok=True)
PROCESSED_SERVICES_DIR.mkdir(parents=True, exist_ok=True)

RAW_SERVICES_DIR, INTERIM_SERVICES_DIR, PROCESSED_SERVICES_DIR

Using PROJECT_ROOT: /Users/laurenvo/Documents/github/Mapping-Youth-Opportunity-Deserts

(PosixPath('/Users/laurenvo/Documents/github/Mapping-Youth-Opportunity-Deserts/data/raw/services'),
 PosixPath('/Users/laurenvo/Documents/github/Mapping-Youth-Opportunity-Deserts/data/interim/services'),
 PosixPath('/Users/laurenvo/Documents/github/Mapping-Youth-Opportunity-Deserts/data/processed/services'))

In [29]:
import re

def clean_zip(value):
    """Extract a 5-digit ZIP code as a string; return NaN if not found."""
    if pd.isna(value):
        return np.nan
    s = str(value)
    m = re.search(r"\d{5}", s)
    return m.group(0) if m else np.nan

def standardize_phone(value):
    """Simple phone cleaner: strip whitespace; leave formatting as is."""
    if pd.isna(value):
        return np.nan
    return str(value).strip()

def lower_strip(series):
    """Lowercase + strip string Series safely."""
    return series.astype(str).str.strip().str.lower()

def summarize_dataset(df, name):
    """Quick text summary for EDA."""
    print(f"\n=== {name} ===")
    print("Shape:", df.shape)
    print("Columns:", list(df.columns))
    print(df.head(3))
    print("\nMissing values (%):")
    print((df.isna().mean() * 100).round(1))

In [30]:
# File names (as they appear in data/raw/services)
paths = {
    "ymca": RAW_SERVICES_DIR / "ymca_sd.csv",
    "sd_public_libraries": RAW_SERVICES_DIR / "sd_public_libraries.csv",
    "library_all": RAW_SERVICES_DIR / "Library.csv",
    "parks": RAW_SERVICES_DIR / "Parks_SD.csv",
    "rec_centers_src1": RAW_SERVICES_DIR / "rec_centers_datasd.csv",
    "rec_centers_src2": RAW_SERVICES_DIR / "Recreation_Centers_SD.csv",
    "gtfs_routes": RAW_SERVICES_DIR / "Transit_Routes_GTFS.csv",
    "gtfs_stops": RAW_SERVICES_DIR / "Transit_Stops_GTFS_20251028.csv",
}

raw = {name: pd.read_csv(path, low_memory=False) for name, path in paths.items()}

for name, df in raw.items():
    summarize_dataset(df, name)

=== ymca ===
Shape: (23, 10)
Columns: ['org', 'name', 'address', 'city', 'state', 'zip', 'phone', 'fax', 'website', 'source']
                        org                      name                  address       city state    zip           phone             fax  \
0  YMCA of San Diego County   Border View Family YMCA          3601 Arey Drive  San Diego    CA  91154  (619) 428-9622  (619) 298-9262
1  YMCA of San Diego County       Cameron Family YMCA    10123 Riverwalk Drive     Santee    CA  92071  (619) 449-9622  (619) 449-9624
2  YMCA of San Diego County  Copley-Price Family YMCA  4300 El Cajon Boulevard  San Diego    CA  92105  (619) 280-9622  (619) 283-7586

                                             website                             source
0  https://www.ymcasd.org/locations/border-view-f...  https://www.ymcasd.org/locations/
1  https://www.ymcasd.org/locations/cameron-famil...  https://www.ymcasd.org/locations/
2  https://www.ymcasd.org/locations/copley-price-...  https://www.ymcasd.org/locations/

Missing values (%):
org         0.0
name        0.0
address     0.0
city        0.0
state       0.0
zip         0.0
phone       4.3
fax        34.8
website     0.0
source      0.0
dtype: float64

=== sd_public_libraries ===
Shape: (38, 9)
Columns: ['org', 'name', 'address', 'city', 'state', 'zip', 'phone', 'website', 'source']
                        org                             name                 address       city state    zip           phone  \
0  San Diego Public Library                  Central Library           330 Park Blvd  San Diego    CA  92101  (619) 236-5800
1  San Diego Public Library  Allied Gardens/Benjamin Library           5188 Zion Ave  San Diego    CA  92120  (619) 533-3970
2  San Diego Public Library                   Balboa Library  4255 Mt. Abernathy Ave  San Diego    CA  92117  (858) 573-1390

                                             website                                             source
0  https://www.sandiego.gov/public-library/centra...  https://sandiego.librarymarket.com/branches/se...
1                                                NaN  https://sandiego.librarymarket.com/branches/se...
2                                                NaN  https://sandiego.librarymarket.com/branches/se...

Missing values (%):
org         0.0
name        0.0
address     0.0
city        0.0
state       0.0
zip         0.0
phone       2.6
website    86.8
source      2.6
dtype: float64

=== library_all ===
Shape: (92, 11)
Columns: ['OID_', 'WEBSITE', 'ADDRESS', 'DISTRICT', 'NAME', 'TYPE', 'PHONE', 'ZIP', 'CITY', 'DATA_SRC', 'UPDATE_DATE']
   OID_                                           WEBSITE            ADDRESS     DISTRICT                      NAME    TYPE  \
0     1  https://www.chulavistaca.gov/departments/library       365 F Street  Chula Vista       Civic Center Branch  Public
1     2  https://www.chulavistaca.gov/departments/library  389 Orange Avenue  Chula Vista  South Chula Vista Branch  Public
2     3                      https://coronadolibrary.org/  640 Orange Avenue     Coronado           Coronado Public  Public

            PHONE    ZIP             CITY                  DATA_SRC         UPDATE_DATE
0  (619) 691-5069  91910  Chula Vista, CA               Chula Vista  7/25/2023 14:09:20
1  (619) 585-5755  91911  Chula Vista, CA               Chula Vista  7/25/2023 14:09:25
2  (619) 522-7390  92118     Coronado, CA  City of Coronado website  7/25/2023 13:36:25

Missing values (%):
OID_           0.0
WEBSITE        0.0
ADDRESS        0.0
DISTRICT       0.0
NAME           0.0
TYPE           2.2
PHONE          4.3
ZIP            0.0
CITY           0.0
DATA_SRC       1.1
UPDATE_DATE    1.1
dtype: float64

=== parks ===
Shape: (301, 51)
Columns: ['objectid', 'common_name', 'desig_use', 'acres', 'address_lo', 'community', 'use_restriction', 'dedicated_park', 'full_name', 'undeveloped_ac', 'useable_ac', 'gross_ac', 'maint_entity', 'recycled_water', 'play_area_cnt', 'cd', 'dms', 'x_coord', 'y_coord', 'year_acquired', 'read_ac', 'notes', 'year_constructed', 'year_assessed', 'pci', 'service_district', 'playground', 'tot_lot', 'baseball_50_6', 'baseball_90', 'softball', 'multi_purpose', 'f_2_baselet', 'basketball', 'tennis', 'sand_vball', 'comfort_station', 'concession_stand', 'pickleball', 'field_lighting_cnt', 'field_lighting', 'created_user', 'created_date', 'last_edited_user', 'last_edited_date', 'globalid', 'crg', 'gdp_url', 'fitness_st', 'shape_Length', 'shape_Area']
   objectid                 common_name          desig_use      acres                   address_lo               community  \
0         1                 OAK PARK NP  Neighborhood Park   3.488897       5235 Maple St. , 92105  MID-CITY: EASTERN AREA
1         2  SAN CARLOS CP & REC CENTER     Community Park   9.788830  6445 Lake Badin Ave., 92119                  NAVAJO
2         3                    MARCY NP  Neighborhood Park  10.887424    5526 STRESEMANN ST, 92122              UNIVERSITY

      use_restriction dedicated_park                                      full_name  undeveloped_ac  useable_ac  gross_ac maint_entity  \
0   DEDIC PK/OS--ORD.              Y                          Oak Neighborhood Park             0.0         0.0       0.0          CP2
1   DEDIC PK/OS--ORD.              Y  San Carlos Community Park & Recreation Center             0.0         0.0       0.0          CP1
2  VOTER RATIF. REQ'D              Y                        Marcy Neighborhood Park             0.0         0.0       0.0          CP1

  recycled_water  play_area_cnt  cd                               dms     x_coord    y_coord year_acquired  read_ac notes  \
0              N            1.0   4  32 43 57.17844N 117 04 58.82675W -117.083007  32.732550          1949    3.460   NaN
1              N            1.0   7  32 47 55.12525N 117 01 16.13407W -117.021148  32.798646     1961-1976   10.153   NaN
2              N            1.0   6  32 50 42.50195N 117 13 37.81278W -117.227170  32.845139          1961   10.960   NaN

  year_constructed  year_assessed pci  service_district  playground  tot_lot  baseball_50_6  baseball_90  softball  multi_purpose  \
0             1974         2018.0  15              41.0           1        0              0            0         1              0
1             1967         2015.0  10              45.0           1        1              0            0         2              1
2             1964         2015.0  29              44.0           1        0              0            0         0              0

   f_2_baselet  basketball  tennis  sand_vball  comfort_station  concession_stand  pickleball  field_lighting_cnt field_lighting  \
0            0           0       0           0                0                 0           0                 0.0              N
1            0           2       0           0                0                 0           0                 0.0              N
2            0           0       0           0                0                 0           0                 0.0              N

  created_user created_date last_edited_user    last_edited_date                                globalid             crg  \
0          NaN          NaN           RSAIGA  11/6/2023 23:37:14  {778A7D4D-2CFB-42A5-B8C7-FC2B67CD579F}  Colina Del Sol
1          NaN          NaN           RSAIGA  11/6/2023 23:37:14  {7F9F8E68-130C-4201-8D72-D6834E38A633}      San Carlos
2          NaN          NaN           RSAIGA  11/6/2023 23:37:14  {C74D60C3-B4BF-431D-8D1B-A41EAA729F05}        Standley

                                             gdp_url  fitness_st  shape_Length     shape_Area
0  https://www.sandiego.gov/sites/default/files/p...           0   1560.601140  151975.743542
1  https://www.sandiego.gov/sites/default/files/p...           0   2651.794044  426399.726939
2  https://www.sandiego.gov/sites/default/files/p...           0   3709.224462  474254.282819

Missing values (%):
objectid               0.0
common_name            0.0
desig_use              0.0
acres                  0.0
address_lo             0.7
community              0.0
use_restriction        1.0
dedicated_park         8.6
full_name              0.0
undeveloped_ac         0.0
useable_ac            11.6
gross_ac              12.0
maint_entity           0.0
recycled_water         9.6
play_area_cnt          8.0
cd                     0.0
dms                    7.6
x_coord                4.7
y_coord                4.7
year_acquired         20.6
read_ac               17.9
notes                 71.4
year_constructed      18.3
year_assessed         22.6
pci                   22.9
service_district       0.3
playground             0.0
tot_lot                0.0
baseball_50_6          0.0
baseball_90            0.0
softball               0.0
multi_purpose          0.0
f_2_baselet            0.0
basketball             0.0
tennis                 0.0
sand_vball             0.0
comfort_station        0.0
concession_stand       0.0
pickleball             0.0
field_lighting_cnt     8.3
field_lighting         0.3
created_user          99.3
created_date          99.3
last_edited_user       0.0
last_edited_date       0.0
globalid               0.0
crg                    9.0
gdp_url               19.6
fitness_st             0.0
shape_Length           0.0
shape_Area             0.0
dtype: float64

=== rec_centers_src1 ===
Shape: (64, 28)
Columns: ['objectid', 'rec_bldg', 'park_name', 'fac_nm_id', 'address', 'zip', 'sq_ft', 'year_built', 'serv_dist', 'adult_ctr', 'comfort_st', 'comp_room', 'dance_rm', 'game_room', 'gymnasium', 'kiln', 'kiln_room', 'kitchen', 'multi_purp', 'racquetbll', 'stage', 'teen_ctr', 'tinytot_rm', 'weight_rm', 'cd', 'neighborhd', 'lat', 'lng']
   objectid                                      rec_bldg                         park_name  fac_nm_id                  address    zip  \
0         1         Bay TerracesCommunity & Senior Center                   Bay Terraces CP    10997.0            7445 Tooma St  92139
1         2  Park de la Cruz Gymnasium & Community Center  Park de la Cruz Neighbohood Park    10751.0     3901 Landis Steet St  92105
2         3                        San Ysidro Teen Center                     San Ysidro CP      473.0  101 W. San Ysidro Blvd.  92173

    sq_ft  year_built serv_dist  adult_ctr  comfort_st  comp_room  dance_rm  game_room  gymnasium  kiln  kiln_room  kitchen  multi_purp  \
0  5220.0      2020.0        43        1.0           1        0.0       0.0        0.0        0.0   0.0        0.0      1.0         1.0
1     NaN      2019.0        41        0.0           1        1.0       1.0        0.0        1.0   0.0        0.0      1.0         4.0
2  4048.0      1924.0        42        0.0           1        1.0       0.0        1.0        0.0   0.0        0.0      0.0         1.0

   racquetbll  stage  teen_ctr  tinytot_rm  weight_rm  cd      neighborhd        lat         lng
0         0.0    0.0       0.0         1.0        0.0   4    BAY TERRACES  32.680795 -117.035576
1         0.0    0.0       0.0         0.0        1.0   9  CHEROKEE POINT  32.745716 -117.110321
2         0.0    0.0       1.0         0.0        0.0   8      SAN YSIDRO  32.552678 -117.044289

Missing values (%):
objectid      0.0
rec_bldg      0.0
park_name     0.0
fac_nm_id     4.7
address       0.0
zip           0.0
sq_ft         6.2
year_built    6.2
serv_dist     0.0
adult_ctr     4.7
comfort_st    0.0
comp_room     4.7
dance_rm      4.7
game_room     4.7
gymnasium     4.7
kiln          4.7
kiln_room     4.7
kitchen       4.7
multi_purp    4.7
racquetbll    4.7
stage         4.7
teen_ctr      3.1
tinytot_rm    3.1
weight_rm     4.7
cd            0.0
neighborhd    0.0
lat           0.0
lng           0.0
dtype: float64

=== rec_centers_src2 ===
Shape: (61, 36)
Columns: ['objectid', 'rec_bldg', 'park_name', 'address', 'city', 'zipcode', 'square_feet', 'year_built', 'adult_center', 'comfort_station', 'comp_room', 'dance_room', 'game_room', 'gymnasium', 'kiln', 'kiln_room', 'kitchen', 'multi_purpose', 'racquetball', 'stage', 'teen_center', 'tiny_tot_room', 'weight_room', 'neighborhood', 'cd', 'service_district', 'indoor_bball', 'indoor_vball', 'indoor_pickleball', 'notes', 'maint_entity', 'community', 'facility_name_id', 'globalid', 'x', 'y']
   objectid                  rec_bldg                     park_name                address       city  zipcode  square_feet  year_built  \
0         1  Scripps Ranch Rec Center  Scripps Ranch Community Park  11454 Blue Cypress Dr  San Diego    92131      12080.0      2000.0
1         2     North Park Rec Center     North Park Community Park          4044 Idaho St  San Diego    92104      11230.0      1947.0
2         3     Southcrest Rec Center     Southcrest Community Park         4149 Newton Av  San Diego    92113      10620.0      1964.0

   adult_center  comfort_station  comp_room  dance_room  game_room  gymnasium  kiln  kiln_room  kitchen  multi_purpose  racquetball  \
0           0.0              0.0        0.0         0.0        0.0        1.0   0.0        0.0      1.0            2.0          0.0
1           1.0              0.0        0.0         1.0        1.0        1.0   1.0        1.0      1.0            3.0          0.0
2           0.0              0.0        0.0         0.0        1.0        1.0   1.0        0.0      1.0            2.0          0.0

   stage  teen_center  tiny_tot_room  weight_room         neighborhood  cd  service_district  indoor_bball  indoor_vball  \
0    0.0          0.0            0.0          0.0  MIRAMAR RANCH NORTH   5                40             3             1
1    0.0          1.0            1.0          0.0           NORTH PARK   3                41             3             1
2    0.0          1.0            0.0          1.0           SOUTHCREST   8                43             1             1

   indoor_pickleball notes maint_entity               community  facility_name_id                                globalid             x  \
0                  4   NaN          CP1     MIRAMAR RANCH NORTH           10279.0  {F5B6A5AD-F661-4A13-A550-7686028B4A80}  6.307032e+06
1                  0   NaN          CP2              NORTH PARK             488.0  {70FC966B-5EBC-4C69-8833-B21F71208AEB}  6.289815e+06
2                  0   NaN          CP2  SOUTHEASTERN SAN DIEGO             299.0  {DA01898D-C205-49DD-873D-CEEDD3E12FA5}  6.298743e+06

              y
0  1.918689e+06
1  1.854146e+06
2  1.833466e+06

Missing values (%):
objectid              0.0
rec_bldg              0.0
park_name             0.0
address               0.0
city                  0.0
zipcode               0.0
square_feet           3.3
year_built            1.6
adult_center          1.6
comfort_station       1.6
comp_room             1.6
dance_room            1.6
game_room             1.6
gymnasium             1.6
kiln                  1.6
kiln_room             1.6
kitchen               1.6
multi_purpose         1.6
racquetball           1.6
stage                 1.6
teen_center           1.6
tiny_tot_room         1.6
weight_room           1.6
neighborhood          0.0
cd                    0.0
service_district      0.0
indoor_bball          0.0
indoor_vball          0.0
indoor_pickleball     0.0
notes                98.4
maint_entity          0.0
community             0.0
facility_name_id      1.6
globalid              0.0
x                     0.0
y                     0.0
dtype: float64

=== gtfs_routes ===
Shape: (478, 16)
Columns: ['OID_', 'shape_id', 'route_id', 'route_short_name', 'route_long_name', 'route_type', 'agency_id', 'route_desc', 'route_url', 'route_color', 'route_text_color', 'route_type_text', 'RouteShapeName', 'route_color_RGB', 'route_text_color_RGB', 'Shape_Length']
   OID_ shape_id route_id route_short_name          route_long_name  route_type agency_id  route_desc                     route_url  \
0     1  3010111      301              101  Oceanside - UTC/VA/UCSD           3      NCTD         NaN  http://www.gonctd.com/breeze
1     2  3010125      301              101  Oceanside - UTC/VA/UCSD           3      NCTD         NaN  http://www.gonctd.com/breeze
2     3  3010130      301              101  Oceanside - UTC/VA/UCSD           3      NCTD         NaN  http://www.gonctd.com/breeze

  route_color route_text_color route_type_text RouteShapeName route_color_RGB route_text_color_RGB   Shape_Length
0      008C9B           FFFFFF             Bus    3010111_301     (0, 0, 153)      (255, 255, 255)   64299.022185
1      008C9B           FFFFFF             Bus    3010125_301     (0, 0, 153)      (255, 255, 255)   65023.903782
2      008C9B           FFFFFF             Bus    3010130_301     (0, 0, 153)      (255, 255, 255)  149486.999710

Missing values (%):
OID_                      0.0
shape_id                  0.0
route_id                  0.0
route_short_name          1.3
route_long_name           0.0
route_type                0.0
agency_id                 0.0
route_desc              100.0
route_url                 0.0
route_color               0.0
route_text_color          0.0
route_type_text           0.0
RouteShapeName            0.0
route_color_RGB           0.6
route_text_color_RGB      0.0
Shape_Length              0.0
dtype: float64

=== gtfs_stops ===
Shape: (6230, 14)
Columns: ['the_geom', 'OBJECTID', 'stop_UID', 'stop_agency', 'stop_id', 'stop_name', 'stop_lat', 'stop_lon', 'stop_code', 'location_type', 'parent_station', 'wheelchair_boarding', 'intersection_code', 'stop_place']
                                    the_geom OBJECTID    stop_UID stop_agency stop_id                stop_name   stop_lat    stop_lon  \
0  POINT (-117.225253999814 33.289260000306)    5,239  NCTD_21699        NCTD   21699  Hwy 76 & Camino Del Rey  33.289260 -117.225254
1  POINT (-117.090831370467 32.658396440078)    1,947   MTS_12532         MTS   12532    Highland Av & 30th St  32.658396 -117.090831
2  POINT (-117.146401100416 32.753688689998)    3,404   MTS_13553         MTS   13553      Park Bl & Howard Av  32.753689 -117.146401

   stop_code  location_type parent_station  wheelchair_boarding intersection_code stop_place
0    21699.0              0            NaN                  NaN             F-N/B     miscam
1    12532.0              0            NaN                  1.0             N-N/B     high30
2    13553.0              0            NaN                  0.0             F-S/B        NaN

Missing values (%):
the_geom                0.0
OBJECTID                0.0
stop_UID                0.0
stop_agency             0.0
stop_id                 0.0
stop_name               0.0
stop_lat                0.0
stop_lon                0.0
stop_code               1.8
location_type           0.0
parent_station         95.1
wheelchair_boarding    29.5
intersection_code       5.3
stop_place             72.8
dtype: float64

In [31]:
ymca = raw["ymca"].copy()

# Basic cleaning
ymca["zip"] = ymca["zip"].apply(clean_zip)
ymca["phone"] = ymca["phone"].apply(standardize_phone)
ymca["fax"] = ymca["fax"].apply(standardize_phone)

# Add required columns that don't exist yet
ymca["lat"] = np.nan
ymca["lon"] = np.nan
ymca["hours"] = np.nan
ymca["eligibility"] = np.nan
ymca["service_type"] = "ymca"

# Column order 
ymca = ymca[
    [
        "service_type",
        "org",
        "name",
        "address",
        "city",
        "state",
        "zip",
        "lat",
        "lon",
        "phone",
        "fax",
        "website",
        "hours",
        "eligibility",
        "source",
    ]
]

summarize_dataset(ymca, "YMCA (clean)")
ymca.to_csv(INTERIM_SERVICES_DIR / "ymca_clean.csv", index=False)

=== YMCA (clean) ===
Shape: (23, 15)
Columns: ['service_type', 'org', 'name', 'address', 'city', 'state', 'zip', 'lat', 'lon', 'phone', 'fax', 'website', 'hours', 'eligibility', 'source']
  service_type                       org                      name                  address       city state    zip  lat  lon  \
0         ymca  YMCA of San Diego County   Border View Family YMCA          3601 Arey Drive  San Diego    CA  91154  NaN  NaN
1         ymca  YMCA of San Diego County       Cameron Family YMCA    10123 Riverwalk Drive     Santee    CA  92071  NaN  NaN
2         ymca  YMCA of San Diego County  Copley-Price Family YMCA  4300 El Cajon Boulevard  San Diego    CA  92105  NaN  NaN

            phone             fax                                            website  hours  eligibility  \
0  (619) 428-9622  (619) 298-9262  https://www.ymcasd.org/locations/border-view-f...    NaN          NaN
1  (619) 449-9622  (619) 449-9624  https://www.ymcasd.org/locations/cameron-famil...    NaN          NaN
2  (619) 280-9622  (619) 283-7586  https://www.ymcasd.org/locations/copley-price-...    NaN          NaN

                              source
0  https://www.ymcasd.org/locations/
1  https://www.ymcasd.org/locations/
2  https://www.ymcasd.org/locations/

Missing values (%):
service_type      0.0
org               0.0
name              0.0
address           0.0
city              0.0
state             0.0
zip               0.0
lat             100.0
lon             100.0
phone             4.3
fax              34.8
website           0.0
hours           100.0
eligibility     100.0
source            0.0
dtype: float64

In [32]:
sdpl = raw["sd_public_libraries"].copy()

sdpl["zip"] = sdpl["zip"].apply(clean_zip)
sdpl["phone"] = sdpl["phone"].apply(standardize_phone)

sdpl["fax"] = np.nan
sdpl["lat"] = np.nan
sdpl["lon"] = np.nan
sdpl["hours"] = np.nan
sdpl["eligibility"] = np.nan
sdpl["service_type"] = "library"

sdpl = sdpl[
    [
        "service_type",
        "org",
        "name",
        "address",
        "city",
        "state",
        "zip",
        "lat",
        "lon",
        "phone",
        "fax",
        "website",
        "hours",
        "eligibility",
        "source",
    ]
]

summarize_dataset(sdpl, "SD Public Libraries (clean)")
sdpl.to_csv(INTERIM_SERVICES_DIR / "sd_public_libraries_clean.csv", index=False)

=== SD Public Libraries (clean) ===
Shape: (38, 15)
Columns: ['service_type', 'org', 'name', 'address', 'city', 'state', 'zip', 'lat', 'lon', 'phone', 'fax', 'website', 'hours', 'eligibility', 'source']
  service_type                       org                             name                 address       city state    zip  lat  lon  \
0      library  San Diego Public Library                  Central Library           330 Park Blvd  San Diego    CA  92101  NaN  NaN
1      library  San Diego Public Library  Allied Gardens/Benjamin Library           5188 Zion Ave  San Diego    CA  92120  NaN  NaN
2      library  San Diego Public Library                   Balboa Library  4255 Mt. Abernathy Ave  San Diego    CA  92117  NaN  NaN

            phone  fax                                            website  hours  eligibility  \
0  (619) 236-5800  NaN  https://www.sandiego.gov/public-library/centra...    NaN          NaN
1  (619) 533-3970  NaN                                                NaN    NaN          NaN
2  (858) 573-1390  NaN                                                NaN    NaN          NaN

                                              source
0  https://sandiego.librarymarket.com/branches/se...
1  https://sandiego.librarymarket.com/branches/se...
2  https://sandiego.librarymarket.com/branches/se...

Missing values (%):
service_type      0.0
org               0.0
name              0.0
address           0.0
city              0.0
state             0.0
zip               0.0
lat             100.0
lon             100.0
phone             2.6
fax             100.0
website          86.8
hours           100.0
eligibility     100.0
source            2.6
dtype: float64

In [33]:
lib = raw["library_all"].copy()

# Infer org: for San Diego city libraries, label consistently
lib["org"] = np.where(
    lib["DISTRICT"].str.contains("San Diego Public", case=False, na=False),
    "San Diego Public Library",
    lib["DISTRICT"],
)

lib["name"] = lib["NAME"]
lib["address"] = lib["ADDRESS"]
lib["city"] = lib["CITY"].str.replace(", CA", "", regex=False).str.strip()
lib["state"] = "CA"
lib["zip"] = lib["ZIP"].apply(clean_zip)
lib["phone"] = lib["PHONE"].apply(standardize_phone)
lib["website"] = lib["WEBSITE"]
lib["source"] = lib["DATA_SRC"]

# Add missing fields
for col in ["fax", "lat", "lon", "hours", "eligibility"]:
    lib[col] = np.nan

lib["service_type"] = "library"

lib_clean = lib[
    [
        "service_type",
        "org",
        "name",
        "address",
        "city",
        "state",
        "zip",
        "lat",
        "lon",
        "phone",
        "fax",
        "website",
        "hours",
        "eligibility",
        "source",
    ]
]

summarize_dataset(lib_clean, "Library.csv (clean, before dedupe)")
lib_clean.to_csv(INTERIM_SERVICES_DIR / "library_multi_jur_clean.csv", index=False)

# Merge with SDPL & deduplicate
libraries_all = pd.concat([sdpl, lib_clean], ignore_index=True)

# Make a deduplication key: org + name + ZIP (normalized)
for col in ["org", "name", "zip"]:
    libraries_all[col] = libraries_all[col].astype(str).str.strip()

dedupe_key = (
    lower_strip(libraries_all["org"])
    + " | "
    + lower_strip(libraries_all["name"])
    + " | "
    + libraries_all["zip"].fillna("")
)

libraries_all["dedupe_key"] = dedupe_key

# Keep the first occurrence of each key
libraries_all = libraries_all.sort_values(["org", "name"]).drop_duplicates(
    subset=["dedupe_key"], keep="first"
)

libraries_all = libraries_all.drop(columns=["dedupe_key"])

summarize_dataset(libraries_all, "Libraries (merged + deduped)")

libraries_all.to_csv(PROCESSED_SERVICES_DIR / "libraries_all_clean.csv", index=False)

=== Library.csv (clean, before dedupe) ===
Shape: (92, 15)
Columns: ['service_type', 'org', 'name', 'address', 'city', 'state', 'zip', 'lat', 'lon', 'phone', 'fax', 'website', 'hours', 'eligibility', 'source']
  service_type          org                      name            address         city state    zip  lat  lon           phone  fax  \
0      library  Chula Vista       Civic Center Branch       365 F Street  Chula Vista    CA  91910  NaN  NaN  (619) 691-5069  NaN
1      library  Chula Vista  South Chula Vista Branch  389 Orange Avenue  Chula Vista    CA  91911  NaN  NaN  (619) 585-5755  NaN
2      library     Coronado           Coronado Public  640 Orange Avenue     Coronado    CA  92118  NaN  NaN  (619) 522-7390  NaN

                                            website  hours  eligibility                    source
0  https://www.chulavistaca.gov/departments/library    NaN          NaN               Chula Vista
1  https://www.chulavistaca.gov/departments/library    NaN          NaN               Chula Vista
2                      https://coronadolibrary.org/    NaN          NaN  City of Coronado website

Missing values (%):
service_type      0.0
org               0.0
name              0.0
address           0.0
city              0.0
state             0.0
zip               0.0
lat             100.0
lon             100.0
phone             4.3
fax             100.0
website           0.0
hours           100.0
eligibility     100.0
source            1.1
dtype: float64

=== Libraries (merged + deduped) ===
Shape: (130, 15)
Columns: ['service_type', 'org', 'name', 'address', 'city', 'state', 'zip', 'lat', 'lon', 'phone', 'fax', 'website', 'hours', 'eligibility', 'source']
   service_type       org                     name                   address      city state    zip  lat  lon          phone  fax  \
80      library  Carlsbad    Carlsbad City Library            1775 Dove Lane  Carlsbad    CA  92011  NaN  NaN  (442)339-2049  NaN
81      library  Carlsbad    Georgina Cole Library  1250 Carlsbad Village Dr  Carlsbad    CA  92008  NaN  NaN  (442)339-2870  NaN
82      library  Carlsbad  Library Learning Center            3368 Eureka Pl  Carlsbad    CA  92008  NaN  NaN  (442)339-5500  NaN

                                       website  hours  eligibility    source
80  https://library.carlsbadca.gov/our-library    NaN          NaN  Carlsbad
81  https://library.carlsbadca.gov/our-library    NaN          NaN  Carlsbad
82  https://library.carlsbadca.gov/our-library    NaN          NaN  Carlsbad

Missing values (%):
service_type      0.0
org               0.0
name              0.0
address           0.0
city              0.0
state             0.0
zip               0.0
lat             100.0
lon             100.0
phone             3.8
fax             100.0
website          25.4
hours           100.0
eligibility     100.0
source            1.5
dtype: float64

In [34]:
lib = raw["library_all"].copy()

# Infer org: for San Diego city libraries, label consistently
lib["org"] = np.where(
    lib["DISTRICT"].str.contains("San Diego Public", case=False, na=False),
    "San Diego Public Library",
    lib["DISTRICT"],
)

lib["name"] = lib["NAME"]
lib["address"] = lib["ADDRESS"]
lib["city"] = lib["CITY"].str.replace(", CA", "", regex=False).str.strip()
lib["state"] = "CA"
lib["zip"] = lib["ZIP"].apply(clean_zip)
lib["phone"] = lib["PHONE"].apply(standardize_phone)
lib["website"] = lib["WEBSITE"]
lib["source"] = lib["DATA_SRC"]

# Add missing fields
for col in ["fax", "lat", "lon", "hours", "eligibility"]:
    lib[col] = np.nan

lib["service_type"] = "library"

lib_clean = lib[
    [
        "service_type",
        "org",
        "name",
        "address",
        "city",
        "state",
        "zip",
        "lat",
        "lon",
        "phone",
        "fax",
        "website",
        "hours",
        "eligibility",
        "source",
    ]
]

summarize_dataset(lib_clean, "Library.csv (clean, before dedupe)")
lib_clean.to_csv(INTERIM_SERVICES_DIR / "library_multi_jur_clean.csv", index=False)

# Merge with SDPL & deduplicate
libraries_all = pd.concat([sdpl, lib_clean], ignore_index=True)

# Make a deduplication key: org + name + ZIP (normalized)
for col in ["org", "name", "zip"]:
    libraries_all[col] = libraries_all[col].astype(str).str.strip()

dedupe_key = (
    lower_strip(libraries_all["org"])
    + " | "
    + lower_strip(libraries_all["name"])
    + " | "
    + libraries_all["zip"].fillna("")
)

libraries_all["dedupe_key"] = dedupe_key

# Keep the first occurrence of each key
libraries_all = libraries_all.sort_values(["org", "name"]).drop_duplicates(
    subset=["dedupe_key"], keep="first"
)

libraries_all = libraries_all.drop(columns=["dedupe_key"])

summarize_dataset(libraries_all, "Libraries (merged + deduped)")

libraries_all.to_csv(PROCESSED_SERVICES_DIR / "libraries_all_clean.csv", index=False)

=== Library.csv (clean, before dedupe) ===
Shape: (92, 15)
Columns: ['service_type', 'org', 'name', 'address', 'city', 'state', 'zip', 'lat', 'lon', 'phone', 'fax', 'website', 'hours', 'eligibility', 'source']
  service_type          org                      name            address         city state    zip  lat  lon           phone  fax  \
0      library  Chula Vista       Civic Center Branch       365 F Street  Chula Vista    CA  91910  NaN  NaN  (619) 691-5069  NaN
1      library  Chula Vista  South Chula Vista Branch  389 Orange Avenue  Chula Vista    CA  91911  NaN  NaN  (619) 585-5755  NaN
2      library     Coronado           Coronado Public  640 Orange Avenue     Coronado    CA  92118  NaN  NaN  (619) 522-7390  NaN

                                            website  hours  eligibility                    source
0  https://www.chulavistaca.gov/departments/library    NaN          NaN               Chula Vista
1  https://www.chulavistaca.gov/departments/library    NaN          NaN               Chula Vista
2                      https://coronadolibrary.org/    NaN          NaN  City of Coronado website

Missing values (%):
service_type      0.0
org               0.0
name              0.0
address           0.0
city              0.0
state             0.0
zip               0.0
lat             100.0
lon             100.0
phone             4.3
fax             100.0
website           0.0
hours           100.0
eligibility     100.0
source            1.1
dtype: float64

=== Libraries (merged + deduped) ===
Shape: (130, 15)
Columns: ['service_type', 'org', 'name', 'address', 'city', 'state', 'zip', 'lat', 'lon', 'phone', 'fax', 'website', 'hours', 'eligibility', 'source']
   service_type       org                     name                   address      city state    zip  lat  lon          phone  fax  \
80      library  Carlsbad    Carlsbad City Library            1775 Dove Lane  Carlsbad    CA  92011  NaN  NaN  (442)339-2049  NaN
81      library  Carlsbad    Georgina Cole Library  1250 Carlsbad Village Dr  Carlsbad    CA  92008  NaN  NaN  (442)339-2870  NaN
82      library  Carlsbad  Library Learning Center            3368 Eureka Pl  Carlsbad    CA  92008  NaN  NaN  (442)339-5500  NaN

                                       website  hours  eligibility    source
80  https://library.carlsbadca.gov/our-library    NaN          NaN  Carlsbad
81  https://library.carlsbadca.gov/our-library    NaN          NaN  Carlsbad
82  https://library.carlsbadca.gov/our-library    NaN          NaN  Carlsbad

Missing values (%):
service_type      0.0
org               0.0
name              0.0
address           0.0
city              0.0
state             0.0
zip               0.0
lat             100.0
lon             100.0
phone             3.8
fax             100.0
website          25.4
hours           100.0
eligibility     100.0
source            1.5
dtype: float64

In [35]:
rec1 = raw["rec_centers_src1"].copy()
rec2 = raw["rec_centers_src2"].copy()

# Rename ID in rec1 so we can merge
rec1 = rec1.rename(columns={"fac_nm_id": "facility_name_id", "zip": "zip_src1"})
rec2 = rec2.rename(columns={"zipcode": "zip_src2"})

# Merge on facility ID + names (this matches the majority of rows)
rec_merged = rec1.merge(
    rec2,
    on=["facility_name_id", "rec_bldg", "park_name"],
    how="outer",
    suffixes=("_src1", "_src2"),
)

# Combine address
rec_merged["address"] = rec_merged["address_src2"].fillna(rec_merged["address_src1"])
rec_merged["city"] = rec_merged["city"].fillna("San Diego")  # default
rec_merged["zip"] = rec_merged["zip_src2"].fillna(rec_merged["zip_src1"])
rec_merged["zip"] = rec_merged["zip"].apply(clean_zip)

# Coordinates: lat/lng from src1 (WGS84), otherwise leave NaN (x,y are in a projected CRS)
rec_merged["lat"] = rec_merged["lat"]
rec_merged["lon"] = rec_merged["lng"]

# Basic org / service info
rec_merged["org"] = "City of San Diego Parks & Recreation"
rec_merged["service_type"] = "rec_center"
rec_merged["name"] = rec_merged["rec_bldg"]

# Square footage
rec_merged["sq_ft"] = rec_merged["sq_ft"].fillna(rec_merged["square_feet"])

# Facility flags – keep as-is but they already match your desired semantics pretty well
facility_cols = [
    "gymnasium",
    "teen_ctr",
    "game_room",
    "multi_purp",
    "multi_purpose",
    "adult_ctr",
    "comfort_st",
    "comfort_station",
    "dance_rm",
    "dance_room",
    "tinytot_rm",
    "tiny_tot_room",
    "weight_rm",
    "weight_room",
]

# Make sure they exist
facility_cols_present = [c for c in facility_cols if c in rec_merged.columns]

# Build a clean subset for analysis
rec_clean_cols = [
    "service_type",
    "org",
    "name",
    "rec_bldg",
    "park_name",
    "address",
    "city",
    "zip",
    "lat",
    "lon",
    "sq_ft",
    "year_built",
    "service_district",
    "community",
    "neighborhood",
    "cd",
]

# Some columns might not exist depending on the merge; guard for that
rec_clean_cols = [c for c in rec_clean_cols if c in rec_merged.columns]

rec_clean = rec_merged[rec_clean_cols + facility_cols_present].copy()
rec_clean["source"] = "rec_centers_datasd + Recreation_Centers_SD"

summarize_dataset(rec_clean, "Recreation Centers (merged)")

rec_clean.to_csv(PROCESSED_SERVICES_DIR / "rec_centers_all_clean.csv", index=False)

=== Recreation Centers (merged) ===
Shape: (67, 27)
Columns: ['service_type', 'org', 'name', 'rec_bldg', 'park_name', 'address', 'city', 'zip', 'lat', 'lon', 'sq_ft', 'service_district', 'community', 'neighborhood', 'teen_ctr', 'multi_purp', 'multi_purpose', 'adult_ctr', 'comfort_st', 'comfort_station', 'dance_rm', 'dance_room', 'tinytot_rm', 'tiny_tot_room', 'weight_rm', 'weight_room', 'source']
  service_type                                   org                  name              rec_bldg                   park_name  \
0   rec_center  City of San Diego Parks & Recreation  Hourglass Rec Center  Hourglass Rec Center  Mira Mesa Communty College
1   rec_center  City of San Diego Parks & Recreation    Encanto Rec Center    Encanto Rec Center      Encanto Community Park
2   rec_center  City of San Diego Parks & Recreation   Encanto Teen Center   Encanto Teen Center      Encanto Community Park

                   address       city    zip        lat         lon    sq_ft  service_district  community neighborhood  teen_ctr  \
0  10440 Black Mountain Rd  San Diego  92126  32.908435 -117.119927  25000.0              44.0  MIRA MESA    MIRA MESA       0.0
1        6508 Wunderlin Av  San Diego  92114  32.714738 -117.057753   9890.0              43.0    ENCANTO      ENCANTO       0.0
2        6508 Wunderlin Av  San Diego  92114  32.715606 -117.056823   1220.0              43.0    ENCANTO      ENCANTO       0.0

   multi_purp  multi_purpose  adult_ctr  comfort_st  comfort_station  dance_rm  dance_room  tinytot_rm  tiny_tot_room  weight_rm  \
0         4.0            4.0        0.0         1.0              0.0       1.0         1.0         0.0            0.0        0.0
1         3.0            3.0        0.0         1.0              0.0       0.0         0.0         0.0            0.0        1.0
2         1.0            1.0        0.0         1.0              0.0       0.0         0.0         0.0            0.0        0.0

   weight_room                                      source
0          0.0  rec_centers_datasd + Recreation_Centers_SD
1          1.0  rec_centers_datasd + Recreation_Centers_SD
2          0.0  rec_centers_datasd + Recreation_Centers_SD

Missing values (%):
service_type         0.0
org                  0.0
name                 0.0
rec_bldg             0.0
park_name            0.0
address              0.0
city                 0.0
zip                  0.0
lat                  4.5
lon                  4.5
sq_ft                7.5
service_district     9.0
community            9.0
neighborhood         9.0
teen_ctr             7.5
multi_purp           9.0
multi_purpose       10.4
adult_ctr            9.0
comfort_st           4.5
comfort_station     10.4
dance_rm             9.0
dance_room          10.4
tinytot_rm           7.5
tiny_tot_room       10.4
weight_rm            9.0
weight_room         10.4
source               0.0
dtype: float64

In [36]:
parks = raw["parks"].copy()

parks["org"] = "City of San Diego Parks & Recreation"
parks["service_type"] = "park"
parks["name"] = parks["full_name"].fillna(parks["common_name"])

# address_lo looks like "5235 Maple St. , 92105"
parks["address"] = parks["address_lo"].str.replace(" ,", ",", regex=False).str.strip()

# Extract ZIP code from address_lo
parks["zip"] = parks["address_lo"].apply(clean_zip)

# Assume city is San Diego for these records
parks["city"] = "San Diego"
parks["state"] = "CA"

# Coordinates
parks["lon"] = parks["x_coord"]
parks["lat"] = parks["y_coord"]

# Facility flags we care about
park_facility_cols = [
    "playground",
    "tot_lot",
    "baseball_50_6",
    "baseball_90",
    "softball",
    "multi_purpose",
    "basketball",
    "tennis",
    "sand_vball",
    "comfort_station",
    "pickleball",
]

park_cols = [
    "service_type",
    "org",
    "name",
    "common_name",
    "full_name",
    "address",
    "city",
    "state",
    "zip",
    "lat",
    "lon",
    "acres",
    "use_restriction",
    "dedicated_park",
    "community",
    "service_district",
]

park_cols = [c for c in park_cols if c in parks.columns]
park_facility_cols_present = [c for c in park_facility_cols if c in parks.columns]

parks_clean = parks[park_cols + park_facility_cols_present].copy()
parks_clean["source"] = "Parks_SD"

summarize_dataset(parks_clean, "Parks (clean)")
parks_clean.to_csv(PROCESSED_SERVICES_DIR / "parks_all_clean.csv", index=False)

=== Parks (clean) ===
Shape: (301, 28)
Columns: ['service_type', 'org', 'name', 'common_name', 'full_name', 'address', 'city', 'state', 'zip', 'lat', 'lon', 'acres', 'use_restriction', 'dedicated_park', 'community', 'service_district', 'playground', 'tot_lot', 'baseball_50_6', 'baseball_90', 'softball', 'multi_purpose', 'basketball', 'tennis', 'sand_vball', 'comfort_station', 'pickleball', 'source']
  service_type                                   org                                           name                 common_name  \
0         park  City of San Diego Parks & Recreation                          Oak Neighborhood Park                 OAK PARK NP
1         park  City of San Diego Parks & Recreation  San Carlos Community Park & Recreation Center  SAN CARLOS CP & REC CENTER
2         park  City of San Diego Parks & Recreation                        Marcy Neighborhood Park                    MARCY NP

                                       full_name                      address       city state    zip        lat         lon      acres  \
0                          Oak Neighborhood Park        5235 Maple St., 92105  San Diego    CA  92105  32.732550 -117.083007   3.488897
1  San Carlos Community Park & Recreation Center  6445 Lake Badin Ave., 92119  San Diego    CA  92119  32.798646 -117.021148   9.788830
2                        Marcy Neighborhood Park    5526 STRESEMANN ST, 92122  San Diego    CA  92122  32.845139 -117.227170  10.887424

      use_restriction dedicated_park               community  service_district  playground  tot_lot  baseball_50_6  baseball_90  softball  \
0   DEDIC PK/OS--ORD.              Y  MID-CITY: EASTERN AREA              41.0           1        0              0            0         1
1   DEDIC PK/OS--ORD.              Y                  NAVAJO              45.0           1        1              0            0         2
2  VOTER RATIF. REQ'D              Y              UNIVERSITY              44.0           1        0              0            0         0

   multi_purpose  basketball  tennis  sand_vball  comfort_station  pickleball    source
0              0           0       0           0                0           0  Parks_SD
1              1           2       0           0                0           0  Parks_SD
2              0           0       0           0                0           0  Parks_SD

Missing values (%):
service_type        0.0
org                 0.0
name                0.0
common_name         0.0
full_name           0.0
address             0.7
city                0.0
state               0.0
zip                 4.0
lat                 4.7
lon                 4.7
acres               0.0
use_restriction     1.0
dedicated_park      8.6
community           0.0
service_district    0.3
playground          0.0
tot_lot             0.0
baseball_50_6       0.0
baseball_90         0.0
softball            0.0
multi_purpose       0.0
basketball          0.0
tennis              0.0
sand_vball          0.0
comfort_station     0.0
pickleball          0.0
source              0.0
dtype: float64

In [37]:
routes = raw["gtfs_routes"].copy()
stops = raw["gtfs_stops"].copy()

# Minimal cleaning: column renaming for clarity
routes_clean = routes.rename(
    columns={
        "route_short_name": "route_short",
        "route_long_name": "route_long",
        "route_type_text": "route_type_text",
    }
).copy()

stops_clean = stops.rename(
    columns={
        "stop_id": "stop_id",
        "stop_name": "stop_name",
        "stop_lat": "lat",
        "stop_lon": "lon",
    }
).copy()

# Convert coordinates to numeric
stops_clean["lat"] = pd.to_numeric(stops_clean["lat"], errors="coerce")
stops_clean["lon"] = pd.to_numeric(stops_clean["lon"], errors="coerce")

summarize_dataset(routes_clean, "GTFS Routes (clean)")
summarize_dataset(stops_clean, "GTFS Stops (clean)")

routes_clean.to_csv(PROCESSED_SERVICES_DIR / "gtfs_routes_clean.csv", index=False)
stops_clean.to_csv(PROCESSED_SERVICES_DIR / "gtfs_stops_clean.csv", index=False)

=== GTFS Routes (clean) ===
Shape: (478, 16)
Columns: ['OID_', 'shape_id', 'route_id', 'route_short', 'route_long', 'route_type', 'agency_id', 'route_desc', 'route_url', 'route_color', 'route_text_color', 'route_type_text', 'RouteShapeName', 'route_color_RGB', 'route_text_color_RGB', 'Shape_Length']
   OID_ shape_id route_id route_short               route_long  route_type agency_id  route_desc                     route_url  \
0     1  3010111      301         101  Oceanside - UTC/VA/UCSD           3      NCTD         NaN  http://www.gonctd.com/breeze
1     2  3010125      301         101  Oceanside - UTC/VA/UCSD           3      NCTD         NaN  http://www.gonctd.com/breeze
2     3  3010130      301         101  Oceanside - UTC/VA/UCSD           3      NCTD         NaN  http://www.gonctd.com/breeze

  route_color route_text_color route_type_text RouteShapeName route_color_RGB route_text_color_RGB   Shape_Length
0      008C9B           FFFFFF             Bus    3010111_301     (0, 0, 153)      (255, 255, 255)   64299.022185
1      008C9B           FFFFFF             Bus    3010125_301     (0, 0, 153)      (255, 255, 255)   65023.903782
2      008C9B           FFFFFF             Bus    3010130_301     (0, 0, 153)      (255, 255, 255)  149486.999710

Missing values (%):
OID_                      0.0
shape_id                  0.0
route_id                  0.0
route_short               1.3
route_long                0.0
route_type                0.0
agency_id                 0.0
route_desc              100.0
route_url                 0.0
route_color               0.0
route_text_color          0.0
route_type_text           0.0
RouteShapeName            0.0
route_color_RGB           0.6
route_text_color_RGB      0.0
Shape_Length              0.0
dtype: float64

=== GTFS Stops (clean) ===
Shape: (6230, 14)
Columns: ['the_geom', 'OBJECTID', 'stop_UID', 'stop_agency', 'stop_id', 'stop_name', 'lat', 'lon', 'stop_code', 'location_type', 'parent_station', 'wheelchair_boarding', 'intersection_code', 'stop_place']
                                    the_geom OBJECTID    stop_UID stop_agency stop_id                stop_name        lat         lon  \
0  POINT (-117.225253999814 33.289260000306)    5,239  NCTD_21699        NCTD   21699  Hwy 76 & Camino Del Rey  33.289260 -117.225254
1  POINT (-117.090831370467 32.658396440078)    1,947   MTS_12532         MTS   12532    Highland Av & 30th St  32.658396 -117.090831
2  POINT (-117.146401100416 32.753688689998)    3,404   MTS_13553         MTS   13553      Park Bl & Howard Av  32.753689 -117.146401

   stop_code  location_type parent_station  wheelchair_boarding intersection_code stop_place
0    21699.0              0            NaN                  NaN             F-N/B     miscam
1    12532.0              0            NaN                  1.0             N-N/B     high30
2    13553.0              0            NaN                  0.0             F-S/B        NaN

Missing values (%):
the_geom                0.0
OBJECTID                0.0
stop_UID                0.0
stop_agency             0.0
stop_id                 0.0
stop_name               0.0
lat                     0.0
lon                     0.0
stop_code               1.8
location_type           0.0
parent_station         95.1
wheelchair_boarding    29.5
intersection_code       5.3
stop_place             72.8
dtype: float64

In [38]:
# All datasets we want in the "services" master
services_parts = []

services_parts.append(ymca)

services_parts.append(
    libraries_all.assign(
        service_type="library"  # ensure tag just in case
    )
)

# For parks & rec centers we need to map columns onto the common schema
def to_common_schema(df, service_type, org_col, name_col, address_col,
                     city_col, state_value="CA", zip_col="zip",
                     lat_col="lat", lon_col="lon",
                     phone_col=None, fax_col=None, website_col=None,
                     extra_cols=None, source_label=None):
    out = pd.DataFrame()
    out["service_type"] = service_type
    out["org"] = df[org_col]
    out["name"] = df[name_col]
    out["address"] = df[address_col]
    out["city"] = df[city_col]
    out["state"] = state_value
    out["zip"] = df[zip_col].apply(clean_zip) if zip_col in df.columns else np.nan
    out["lat"] = df[lat_col] if lat_col in df.columns else np.nan
    out["lon"] = df[lon_col] if lon_col in df.columns else np.nan

    out["phone"] = df[phone_col] if phone_col and phone_col in df.columns else np.nan
    out["fax"] = df[fax_col] if fax_col and fax_col in df.columns else np.nan
    out["website"] = df[website_col] if website_col and website_col in df.columns else np.nan

    out["hours"] = np.nan
    out["eligibility"] = np.nan

    if source_label is not None:
        out["source"] = source_label
    elif "source" in df.columns:
        out["source"] = df["source"]
    else:
        out["source"] = np.nan

    if extra_cols:
        for new_name, col in extra_cols.items():
            out[new_name] = df[col] if col in df.columns else np.nan

    return out

# Rec centers
rec_common = to_common_schema(
    rec_clean,
    service_type="rec_center",
    org_col="org",
    name_col="name",
    address_col="address",
    city_col="city",
    zip_col="zip",
    lat_col="lat",
    lon_col="lon",
    extra_cols={
        "park_name": "park_name",
        "sq_ft": "sq_ft",
    },
    source_label="rec_centers_all_clean",
)

# Parks
parks_common = to_common_schema(
    parks_clean,
    service_type="park",
    org_col="org",
    name_col="name",
    address_col="address",
    city_col="city",
    zip_col="zip",
    lat_col="lat",
    lon_col="lon",
    extra_cols={
        "acres": "acres",
        "community": "community",
        "service_district": "service_district",
    },
    source_label="parks_all_clean",
)

services_parts.extend([rec_common, parks_common])

services_master = pd.concat(services_parts, ignore_index=True)

# Final tidy: clean zips again, ensure numeric lat/lon
services_master["zip"] = services_master["zip"].apply(clean_zip)
services_master["lat"] = pd.to_numeric(services_master["lat"], errors="coerce")
services_master["lon"] = pd.to_numeric(services_master["lon"], errors="coerce")

summarize_dataset(services_master, "Services master (before final dedupe)")

# Remove exact-duplicate rows (if any)
services_master = services_master.drop_duplicates().reset_index(drop=True)

services_master.to_csv(PROCESSED_SERVICES_DIR / "services_master.csv", index=False)
services_master.head()

=== Services master (before final dedupe) ===
Shape: (521, 20)
Columns: ['service_type', 'org', 'name', 'address', 'city', 'state', 'zip', 'lat', 'lon', 'phone', 'fax', 'website', 'hours', 'eligibility', 'source', 'park_name', 'sq_ft', 'acres', 'community', 'service_district']
  service_type                       org                      name                  address       city state    zip  lat  lon  \
0         ymca  YMCA of San Diego County   Border View Family YMCA          3601 Arey Drive  San Diego    CA  91154  NaN  NaN
1         ymca  YMCA of San Diego County       Cameron Family YMCA    10123 Riverwalk Drive     Santee    CA  92071  NaN  NaN
2         ymca  YMCA of San Diego County  Copley-Price Family YMCA  4300 El Cajon Boulevard  San Diego    CA  92105  NaN  NaN

            phone             fax                                            website  hours  eligibility  \
0  (619) 428-9622  (619) 298-9262  https://www.ymcasd.org/locations/border-view-f...    NaN          NaN
1  (619) 449-9622  (619) 449-9624  https://www.ymcasd.org/locations/cameron-famil...    NaN          NaN
2  (619) 280-9622  (619) 283-7586  https://www.ymcasd.org/locations/copley-price-...    NaN          NaN

                              source park_name  sq_ft  acres community  service_district
0  https://www.ymcasd.org/locations/       NaN    NaN    NaN       NaN               NaN
1  https://www.ymcasd.org/locations/       NaN    NaN    NaN       NaN               NaN
2  https://www.ymcasd.org/locations/       NaN    NaN    NaN       NaN               NaN

Missing values (%):
service_type         70.6
org                   0.0
name                  0.0
address               0.4
city                  0.0
state                 0.0
zip                   2.3
lat                  32.6
lon                  32.6
phone                71.8
fax                  97.1
website              77.0
hours               100.0
eligibility         100.0
source                0.4
park_name            87.1
sq_ft                88.1
acres                42.2
community            42.2
service_district     42.4
dtype: float64

,service_type,org,name,address,city,state,zip,lat,lon,phone,fax,website,hours,eligibility,source,park_name,sq_ft,acres,community,service_district
0,ymca,YMCA of San Diego County,Border View Family YMCA,3601 Arey Drive,San Diego,CA,91154,NaN,NaN,(619) 428-9622,(619) 298-9262,https://www.ymcasd.org/locations/border-view-f...,NaN,NaN,https://www.ymcasd.org/locations/,NaN,NaN,NaN,NaN,NaN
1,ymca,YMCA of San Diego County,Cameron Family YMCA,10123 Riverwalk Drive,Santee,CA,92071,NaN,NaN,(619) 449-9622,(619) 449-9624,https://www.ymcasd.org/locations/cameron-famil...,NaN,NaN,https://www.ymcasd.org/locations/,NaN,NaN,NaN,NaN,NaN
2,ymca,YMCA of San Diego County,Copley-Price Family YMCA,4300 El Cajon Boulevard,San Diego,CA,92105,NaN,NaN,(619) 280-9622,(619) 283-7586,https://www.ymcasd.org/locations/copley-price-...,NaN,NaN,https://www.ymcasd.org/locations/,NaN,NaN,NaN,NaN,NaN
3,ymca,YMCA of San Diego County,Dan McKinney Family YMCA,8355 Cliffridge Avenue,La Jolla,CA,92037,NaN,NaN,(858) 453-3483,(858) 452-3761,https://www.ymcasd.org/locations/dan-mckinney-...,NaN,NaN,https://www.ymcasd.org/locations/,NaN,NaN,NaN,NaN,NaN
4,ymca,YMCA of San Diego County,Escondido YMCA – A Campus for Community Well-B...,1050 N. Broadway,Escondido,CA,92026,NaN,NaN,(760) 745-7490,NaN,https://www.ymcasd.org/locations/escondido-ymc...,NaN,NaN,https://www.ymcasd.org/locations/,NaN,NaN,NaN,NaN,NaN

In [39]:
print("Total service sites:", len(services_master))

print("\nCounts by service_type:")
print(services_master["service_type"].value_counts())

print("\nTop providers (org):")
print(services_master["org"].value_counts().head(10))

print("\nMissing coordinates by service_type:")
print(
    services_master.assign(
        lat_missing=services_master["lat"].isna(),
        lon_missing=services_master["lon"].isna(),
    )
    .groupby("service_type")[["lat_missing", "lon_missing"]]
    .mean()
    .mul(100)
    .round(1)
)

print("\nLat/Lon ranges:")
print(services_master["lat"].describe())
print(services_master["lon"].describe())

Total service sites: 521

Counts by service_type:
service_type
library    130
ymca        23
Name: count, dtype: int64

Top providers (org):
org
City of San Diego Parks & Recreation    368
San Diego Public Library                 75
San Diego County                         38
YMCA of San Diego County                 23
Oceanside                                 8
Carlsbad                                  3
Chula Vista                               3
Coronado                                  1
Escondido                                 1
National City                             1
Name: count, dtype: int64

Missing coordinates by service_type:
              lat_missing  lon_missing
service_type
library             100.0        100.0
ymca                100.0        100.0

Lat/Lon ranges:
count    3.510000e+02
mean     5.330029e+03
std      9.924366e+04
min      3.246286e+01
25%      3.271990e+01
50%      3.279124e+01
75%      3.290313e+01
max      1.859362e+06
Name: lat, dtype: float64
count    3.510000e+02
mean     1.777416e+04
std      3.351809e+05
min     -1.172816e+02
25%     -1.172028e+02
50%     -1.171315e+02
75%     -1.170882e+02
max      6.279495e+06
Name: lon, dtype: float64

In [40]:
# A compact table suitable for joining to tracts / exporting to GIS
services_for_mapping = services_master[
    [
        "service_type",
        "org",
        "name",
        "address",
        "city",
        "state",
        "zip",
        "lat",
        "lon",
        "source",
    ]
].copy()

services_for_mapping.to_csv(PROCESSED_SERVICES_DIR / "services_for_mapping.csv", index=False)
services_for_mapping.head()

,service_type,org,name,address,city,state,zip,lat,lon,source
0,ymca,YMCA of San Diego County,Border View Family YMCA,3601 Arey Drive,San Diego,CA,91154,NaN,NaN,https://www.ymcasd.org/locations/
1,ymca,YMCA of San Diego County,Cameron Family YMCA,10123 Riverwalk Drive,Santee,CA,92071,NaN,NaN,https://www.ymcasd.org/locations/
2,ymca,YMCA of San Diego County,Copley-Price Family YMCA,4300 El Cajon Boulevard,San Diego,CA,92105,NaN,NaN,https://www.ymcasd.org/locations/
3,ymca,YMCA of San Diego County,Dan McKinney Family YMCA,8355 Cliffridge Avenue,La Jolla,CA,92037,NaN,NaN,https://www.ymcasd.org/locations/
4,ymca,YMCA of San Diego County,Escondido YMCA – A Campus for Community Well-B...,1050 N. Broadway,Escondido,CA,92026,NaN,NaN,https://www.ymcasd.org/locations/

In [41]:
mask_parksrec = (
    services_master["service_type"].isna()
    & (services_master["org"] == "City of San Diego Parks & Recreation")
)

# building-ish → rec center
services_master.loc[mask_parksrec & services_master["sq_ft"].notna(), "service_type"] = "rec_center"

# land-only → park
services_master.loc[mask_parksrec & services_master["sq_ft"].isna(), "service_type"] = "park"

In [42]:
services_master["service_type"].value_counts(dropna=False)

service_type
park          306
library       130
rec_center     62
ymca           23
Name: count, dtype: int64

In [43]:
zip_num = pd.to_numeric(services_master["zip"], errors="coerce")

bad_zip = (zip_num < 91900) | (zip_num > 92299)
services_master.loc[bad_zip, "zip"] = np.nan

In [44]:
lat_ok = services_master["lat"].between(32, 33.5)
lon_ok = services_master["lon"].between(-117.7, -116)

services_master.loc[~(lat_ok & lon_ok), ["lat", "lon"]] = np.nan

In [45]:
subset_cols = ["service_type", "org", "name", "address", "city", "zip"]

services_master = (
    services_master
    .sort_values(["lat", "lon"], na_position="last")  # rows with lat/lon first
    .drop_duplicates(subset=subset_cols, keep="first")
    .reset_index(drop=True)
)

In [46]:
dup_mask = services_master.duplicated(subset=subset_cols, keep=False)
services_master[dup_mask].sort_values(subset_cols)

Empty DataFrame
Columns: [service_type, org, name, address, city, state, zip, lat, lon, phone, fax, website, hours, eligibility, source, park_name, sq_ft, acres, community, service_district]
Index: []

In [47]:
# Quick check / standardization of service_type 
print("service_type value counts BEFORE standardization:")
print(services_master["service_type"].value_counts(dropna=False))

# Example mapping 
type_map = {
    "Library": "library",
    "library": "library",
    "YMCA": "ymca",
    "Rec Center": "rec_center",
    "Recreation Center": "rec_center",
    "Park": "park",
    "park": "park",
}

services_master["service_type"] = services_master["service_type"].replace(type_map)

service_type value counts BEFORE standardization:
service_type
park          306
library       130
rec_center     61
ymca           23
Name: count, dtype: int64

In [52]:
# Youth-serving flag (heuristic)
services_master["name_lower"] = services_master["name"].astype(str).str.lower()
services_master["org_lower"] = services_master["org"].astype(str).str.lower()

youth_keywords = [
    "youth", "teen", "teens", "after school", "afterschool",
    "boys & girls", "bgc", "club", "mentoring", "mentorship"
]
is_sdys = services_master["org_lower"].str.contains("san diego youth services", na=False)
services_master.loc[is_sdys, "youth_serving"] = True


services_master["youth_serving"] = False
for kw in youth_keywords:
    mask = (
        services_master["name_lower"].str.contains(kw, na=False)
        | services_master["org_lower"].str.contains(kw, na=False)
    )
    services_master.loc[mask, "youth_serving"] = True

# Drop helper cols
services_master = services_master.drop(columns=["name_lower", "org_lower"])

print("Youth-serving site count:", services_master["youth_serving"].sum())

Youth-serving site count: 4

In [49]:
print("Total sites:", len(services_master))

print("\nSites by service_type:")
print(services_master["service_type"].value_counts())

print("\nSites by org (top 10):")
print(services_master["org"].value_counts().head(10))

print("\nMissing coordinates by service_type (%):")
print(
    services_master.assign(
        lat_missing=services_master["lat"].isna(),
        lon_missing=services_master["lon"].isna(),
    )
    .groupby("service_type")[["lat_missing", "lon_missing"]]
    .mean()
    .mul(100)
    .round(1)
)

print("\nParks – acres summary:")
print(
    services_master.loc[services_master["service_type"]=="park", "acres"]
    .describe()
)

print("\nRec centers – sq_ft summary:")
print(
    services_master.loc[services_master["service_type"]=="rec_center", "sq_ft"]
    .describe()
)

Total sites: 520

Sites by service_type:
service_type
park          306
library       130
rec_center     61
ymca           23
Name: count, dtype: int64

Sites by org (top 10):
org
City of San Diego Parks & Recreation    367
San Diego Public Library                 75
San Diego County                         38
YMCA of San Diego County                 23
Oceanside                                 8
Carlsbad                                  3
Chula Vista                               3
Coronado                                  1
Escondido                                 1
National City                             1
Name: count, dtype: int64

Missing coordinates by service_type (%):
              lat_missing  lon_missing
service_type
library             100.0        100.0
park                  5.6          5.6
rec_center            1.6          1.6
ymca                100.0        100.0

Parks – acres summary:
count     301.000000
mean       29.607651
std       246.525183
min         0.008878
25%         1.252079
50%         5.237009
75%        11.569044
max      4109.147682
Name: acres, dtype: float64

Rec centers – sq_ft summary:
count       61.000000
mean     11267.032787
std       7002.841709
min       1220.000000
25%       6300.000000
50%      10808.000000
75%      15040.000000
max      37970.000000
Name: sq_ft, dtype: float64

In [50]:
services_master.to_csv(PROCESSED_SERVICES_DIR / "services_master_cleaned.csv", index=False)